name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Check Translations
        run: bun run check-i18n

      - name: Test
        run: bun run vitest run

      - name: Build for production
        run: bun run build
